#include "MakeCredential.h"

#include <avr/io.h>
#include <util/delay.h>

#include "get_approval.h"
#include "error.h"
#include "weak_prg.h"
#include "manage_credentials.h"
#include "uECC.h"


status_t MakeCredential(uint8_t *hashed_app_id){
    /*led toggles every 500ms until 10s timeout or 
    button is pushed*/
    set_from_make_credential();
    if(get_approval() == STATUS_ERR_APPROVAL)
                    return STATUS_ERR_APPROVAL;
    unset_from_make_credential();

    /*set the rng function for uECC_make_key and 
    ECC_sign*/
    set_rng_type_timer0();
    uECC_set_rng(uECC_rng);

    uint8_t private_key[uECC_curve_private_key_size(uECC_secp160r1())];
    uint8_t public_key[uECC_curve_public_key_size(uECC_secp160r1())];
    

    /*make key couple*/
    if(!uECC_make_key(public_key, private_key, uECC_secp160r1()))
            return STATUS_ERR_CRYPTO_FAILED;
        
    
    /*
    Generate credential_id:
        -reruns only if the
        seed has a bad score
        as described in the 
        weak_prg module
    */
    uint8_t credential_id[CREDENTIAL_ID_SIZE];
    while(!uECC_rng(credential_id, CREDENTIAL_ID_SIZE));

    /*
    Attempts to write in order, private_key,
    hashed_app_id and credential_id in the 
    eeprom.
    */
    status_t status = add_credential(private_key, hashed_app_id, credential_id);

    if(status != STATUS_OK)
            return STATUS_ERR_STORAGE_FULL;

    /*
    Sends:
        -status, at this point status is STATUS_OK.
        -credential_id, which has been filled earlier.
        -public_key, which has been generated by 
        uECC_make_key.
    */
    fwrite(&status, 1,1, stdout);
    fwrite(credential_id, 1, CREDENTIAL_ID_SIZE, stdout);
    fwrite(public_key, 1, 
        uECC_curve_public_key_size(uECC_secp160r1()), stdout);

    return STATUS_OK;
}